kind: Pod
apiVersion: v1
metadata:
  name: multi-containers
  # namespace: expense
  labels:
    component: dev
spec:
  containers:
  - name: nginx
    image: nginx

  - name: almalinux
    image: almalinux:9
    command: ["sleep","10000"]