kind: Pod
apiVersion: v1
metadata:
  name: annotations
  
  annotations:
    buildURL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.docker.com/"

  labels:
    project: expense
    component: backend
    environment: dev

spec:
 containers:
 - name: nginx
   image: nginx