kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
   containers:
   - name: nginx
     image: nginx
     resources:
     # soft limit
       requests:
         memory: "68Mi"
         cpu: "100m"
         ephemeral-storage: "2Gi"
      # hard limit
       limits:
         memory: "120Mi"
         cpu: "150m"
         ephemeral-storage: "4Gi"