kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: nginx

  #these are replicaset labels
  labels:
    app: frontend
    tier: web
    environment: dev

spec: 
# modify replicas accourding to your case
  replicas: 3
  selector:
  # replicasets use these labels to find the pods for creating desired number of replicas
    matchLabels:
      app: frontend
      tier: web 
# pod template

  template:
    metadata:
      labels:
        app: frontend
        tier: web
    spec: 
       containers:
       - name: nginx
         image: nginx